_wandb:
    value:
        cli_version: 0.24.0
        e:
            jptblwzdfgf3ebztndb777a560abc0bf:
                args:
                    - --batch_size=16
                    - --epochs=5
                    - --lr=0.002008902812198394
                    - --optim=SGD
                codePath: src/grape_vine_classification/train_lightning.py
                codePathLocal: src/grape_vine_classification/train_lightning.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1081101176832"
                        used: "16920281088"
                email: antonespholm@gmail.com
                executable: /home/anton_linux/grape_vine_classification_group_51/.venv/bin/python
                git:
                    commit: 9b198afeb1b09c996cd6786219a5ec8110934c4e
                    remote: https://github.com/ML-Ops-Burnsides-Bitches-Group-51/grape_vine_classification_group_51.git
                host: DESKTOP-4UR0G19
                memory:
                    total: "16403087360"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/anton_linux/grape_vine_classification_group_51/src/grape_vine_classification/train_lightning.py
                python: CPython 3.12.3
                root: /home/anton_linux/grape_vine_classification_group_51
                startedAt: "2026-01-15T13:15:52.833763Z"
                writerId: jptblwzdfgf3ebztndb777a560abc0bf
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
                - 105
            "2":
                - 1
                - 9
                - 41
                - 103
                - 105
            "3":
                - 14
            "4": 3.12.3
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 16
epochs:
    value: 5
lr:
    value: 0.002008902812198394
optim:
    value: SGD
