program: src/grape_vine_classification/train_lightning.py
name: sweep1
project: grape_vine_classifocation
method: bayes

command:
  - ${env}
  - ${interpreter}
  - ${program}

metric:
  name: acc
  goal: maximize

parameters:
  optim:
    values: ["Adam","SGD"]
  lr:
    values: [1e-4,1e-3,5e-3]
    # distribution: log_uniform_values
    # min: 0.0001
    # max: 0.1

  batch_size:
    values: [16]

  epochs:
    values: [5]
  pateince:
    values: [3]

run_cap: 10
